# Generated by Django 4.0.2 on 2022-02-15 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smarttasks', '0001_initial'),
        ('watchdog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Child ID')),
                ('nick_name', models.CharField(blank=True, max_length=50, verbose_name='Nickname')),
                ('ip', models.GenericIPAddressField(unique=True, unpack_ipv4=True, verbose_name='IP-Addr of the child')),
                ('isIPStatic', models.BooleanField(verbose_name='Is the IP Static or not?')),
                ('nurse_check_interval', models.IntegerField(verbose_name='Nurse Check Interval Value')),
                ('nurse_check_type', models.IntegerField(max_length=1, verbose_name='Nurse Check Type')),
                ('sidenote', models.TextField(blank=True, verbose_name='Sidenote on the child')),
            ],
            options={
                'verbose_name': 'child',
                'verbose_name_plural': 'children',
            },
        ),
        migrations.CreateModel(
            name='STask_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron', models.FloatField(verbose_name='Timestamp of the scheduled time')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchdog.child', verbose_name='cid of the target child')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttasks.stask', verbose_name='sid of the s task')),
            ],
            options={
                'verbose_name': 'STask and child',
                'verbose_name_plural': 'STasks and Children',
            },
        ),
    ]
