# Generated by Django 4.0.2 on 2022-02-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0003_alter_child_nurse_check_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
