# Generated by Django 4.0.2 on 2022-02-15 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STask',
            fields=[
                ('sid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique ID for the S Task')),
                ('name', models.CharField(max_length=100, unique_for_date=True, verbose_name='Name for the S Task')),
                ('instructions', models.TextField(verbose_name='Instrunctions for the S Task')),
            ],
            options={
                'verbose_name': 'stasks',
                'verbose_name_plural': 'stasks',
            },
        ),
    ]
